-- بذور القوائم المرجعية — بداية إنتاجية قابلة للتعديل من شاشة المدير (تعطيل لا حذف).
-- كلّها ON CONFLICT DO NOTHING ⟵ آمنة التكرار، ولا تلمس صفوفًا قائمة.

-- ═══ صفات القرابة (للولي ولجهة الطوارئ) ═══
INSERT INTO "GuardianRelation" ("id", "nameAr", "ordinal", "isActive") VALUES
  ('rel_father',      'أب',       1, true),
  ('rel_brother',     'أخ',       2, true),
  ('rel_uncle_pat',   'عم',       3, true),
  ('rel_uncle_mat',   'خال',      4, true),
  ('rel_grandfather', 'جد',       5, true),
  ('rel_guardian',    'وصي',      6, true),
  ('rel_other',       'غير ذلك',  7, true)
ON CONFLICT ("nameAr") DO NOTHING;

-- ═══ المراحل الدراسية — إضافة ماجستير/دكتوراه، وإبقاء «غير ذلك» أخيرًا ═══
UPDATE "SchoolStage" SET "ordinal" = 7 WHERE "id" = 'ss_ghayr';
INSERT INTO "SchoolStage" ("id", "nameAr", "ordinal", "isActive") VALUES
  ('ss_master',    'ماجستير', 5, true),
  ('ss_phd',       'دكتوراه', 6, true)
ON CONFLICT ("nameAr") DO NOTHING;

-- ═══ الجنسيات — قائمة دول العالم (ISO 3166) بالأسماء العربية ═══
-- تعطيل البدائل النائبة (سعودي/غير سعودي) لصالح أسماء الدول. (لا حذف — قد ترتبط بطلبات قديمة.)
UPDATE "Nationality" SET "isActive" = false WHERE "id" IN ('nat_saudi', 'nat_nonsaudi');

-- السعودية أولًا (ordinal 1)، ثم بقيّة الدول العربية (2..22)، ثم العالم (100 ⟵ يُرتَّب بالاسم).
INSERT INTO "Nationality" ("id", "nameAr", "ordinal", "isActive") VALUES
  ('nat_sa', 'السعودية', 1, true),
  ('nat_ae', 'الإمارات العربية المتحدة', 2, true),
  ('nat_kw', 'الكويت', 3, true),
  ('nat_qa', 'قطر', 4, true),
  ('nat_bh', 'البحرين', 5, true),
  ('nat_om', 'عُمان', 6, true),
  ('nat_ye', 'اليمن', 7, true),
  ('nat_eg', 'مصر', 8, true),
  ('nat_jo', 'الأردن', 9, true),
  ('nat_ps', 'فلسطين', 10, true),
  ('nat_sy', 'سوريا', 11, true),
  ('nat_lb', 'لبنان', 12, true),
  ('nat_iq', 'العراق', 13, true),
  ('nat_sd', 'السودان', 14, true),
  ('nat_ly', 'ليبيا', 15, true),
  ('nat_tn', 'تونس', 16, true),
  ('nat_dz', 'الجزائر', 17, true),
  ('nat_ma', 'المغرب', 18, true),
  ('nat_mr', 'موريتانيا', 19, true),
  ('nat_so', 'الصومال', 20, true),
  ('nat_dj', 'جيبوتي', 21, true),
  ('nat_km', 'جزر القمر', 22, true),
  ('nat_af', 'أفغانستان', 100, true),
  ('nat_al', 'ألبانيا', 100, true),
  ('nat_ad', 'أندورا', 100, true),
  ('nat_ao', 'أنغولا', 100, true),
  ('nat_ag', 'أنتيغوا وباربودا', 100, true),
  ('nat_ar', 'الأرجنتين', 100, true),
  ('nat_am', 'أرمينيا', 100, true),
  ('nat_au', 'أستراليا', 100, true),
  ('nat_at', 'النمسا', 100, true),
  ('nat_az', 'أذربيجان', 100, true),
  ('nat_bs', 'باهاماس', 100, true),
  ('nat_bd', 'بنغلاديش', 100, true),
  ('nat_bb', 'باربادوس', 100, true),
  ('nat_by', 'بيلاروسيا', 100, true),
  ('nat_be', 'بلجيكا', 100, true),
  ('nat_bz', 'بليز', 100, true),
  ('nat_bj', 'بنين', 100, true),
  ('nat_bt', 'بوتان', 100, true),
  ('nat_bo', 'بوليفيا', 100, true),
  ('nat_ba', 'البوسنة والهرسك', 100, true),
  ('nat_bw', 'بوتسوانا', 100, true),
  ('nat_br', 'البرازيل', 100, true),
  ('nat_bn', 'بروناي', 100, true),
  ('nat_bg', 'بلغاريا', 100, true),
  ('nat_bf', 'بوركينا فاسو', 100, true),
  ('nat_bi', 'بوروندي', 100, true),
  ('nat_cv', 'الرأس الأخضر', 100, true),
  ('nat_kh', 'كمبوديا', 100, true),
  ('nat_cm', 'الكاميرون', 100, true),
  ('nat_ca', 'كندا', 100, true),
  ('nat_cf', 'جمهورية أفريقيا الوسطى', 100, true),
  ('nat_td', 'تشاد', 100, true),
  ('nat_cl', 'تشيلي', 100, true),
  ('nat_cn', 'الصين', 100, true),
  ('nat_co', 'كولومبيا', 100, true),
  ('nat_cg', 'الكونغو', 100, true),
  ('nat_cd', 'جمهورية الكونغو الديمقراطية', 100, true),
  ('nat_cr', 'كوستاريكا', 100, true),
  ('nat_ci', 'ساحل العاج', 100, true),
  ('nat_hr', 'كرواتيا', 100, true),
  ('nat_cu', 'كوبا', 100, true),
  ('nat_cy', 'قبرص', 100, true),
  ('nat_cz', 'التشيك', 100, true),
  ('nat_dk', 'الدنمارك', 100, true),
  ('nat_dm', 'دومينيكا', 100, true),
  ('nat_do', 'جمهورية الدومينيكان', 100, true),
  ('nat_ec', 'الإكوادور', 100, true),
  ('nat_sv', 'السلفادور', 100, true),
  ('nat_gq', 'غينيا الاستوائية', 100, true),
  ('nat_er', 'إريتريا', 100, true),
  ('nat_ee', 'إستونيا', 100, true),
  ('nat_sz', 'إسواتيني', 100, true),
  ('nat_et', 'إثيوبيا', 100, true),
  ('nat_fj', 'فيجي', 100, true),
  ('nat_fi', 'فنلندا', 100, true),
  ('nat_fr', 'فرنسا', 100, true),
  ('nat_ga', 'الغابون', 100, true),
  ('nat_gm', 'غامبيا', 100, true),
  ('nat_ge', 'جورجيا', 100, true),
  ('nat_de', 'ألمانيا', 100, true),
  ('nat_gh', 'غانا', 100, true),
  ('nat_gr', 'اليونان', 100, true),
  ('nat_gd', 'غرينادا', 100, true),
  ('nat_gt', 'غواتيمالا', 100, true),
  ('nat_gn', 'غينيا', 100, true),
  ('nat_gw', 'غينيا بيساو', 100, true),
  ('nat_gy', 'غيانا', 100, true),
  ('nat_ht', 'هايتي', 100, true),
  ('nat_hn', 'هندوراس', 100, true),
  ('nat_hu', 'المجر', 100, true),
  ('nat_is', 'آيسلندا', 100, true),
  ('nat_in', 'الهند', 100, true),
  ('nat_id', 'إندونيسيا', 100, true),
  ('nat_ir', 'إيران', 100, true),
  ('nat_ie', 'أيرلندا', 100, true),
  ('nat_it', 'إيطاليا', 100, true),
  ('nat_jm', 'جامايكا', 100, true),
  ('nat_jp', 'اليابان', 100, true),
  ('nat_kz', 'كازاخستان', 100, true),
  ('nat_ke', 'كينيا', 100, true),
  ('nat_ki', 'كيريباتي', 100, true),
  ('nat_kp', 'كوريا الشمالية', 100, true),
  ('nat_kr', 'كوريا الجنوبية', 100, true),
  ('nat_kg', 'قيرغيزستان', 100, true),
  ('nat_la', 'لاوس', 100, true),
  ('nat_lv', 'لاتفيا', 100, true),
  ('nat_ls', 'ليسوتو', 100, true),
  ('nat_lr', 'ليبيريا', 100, true),
  ('nat_li', 'ليختنشتاين', 100, true),
  ('nat_lt', 'ليتوانيا', 100, true),
  ('nat_lu', 'لوكسمبورغ', 100, true),
  ('nat_mg', 'مدغشقر', 100, true),
  ('nat_mw', 'مالاوي', 100, true),
  ('nat_my', 'ماليزيا', 100, true),
  ('nat_mv', 'جزر المالديف', 100, true),
  ('nat_ml', 'مالي', 100, true),
  ('nat_mt', 'مالطا', 100, true),
  ('nat_mh', 'جزر مارشال', 100, true),
  ('nat_mx', 'المكسيك', 100, true),
  ('nat_fm', 'ميكرونيزيا', 100, true),
  ('nat_md', 'مولدوفا', 100, true),
  ('nat_mc', 'موناكو', 100, true),
  ('nat_mn', 'منغوليا', 100, true),
  ('nat_me', 'الجبل الأسود', 100, true),
  ('nat_mz', 'موزمبيق', 100, true),
  ('nat_mm', 'ميانمار', 100, true),
  ('nat_na', 'ناميبيا', 100, true),
  ('nat_nr', 'ناورو', 100, true),
  ('nat_np', 'نيبال', 100, true),
  ('nat_nl', 'هولندا', 100, true),
  ('nat_nz', 'نيوزيلندا', 100, true),
  ('nat_ni', 'نيكاراغوا', 100, true),
  ('nat_ne', 'النيجر', 100, true),
  ('nat_ng', 'نيجيريا', 100, true),
  ('nat_mk', 'مقدونيا الشمالية', 100, true),
  ('nat_no', 'النرويج', 100, true),
  ('nat_pk', 'باكستان', 100, true),
  ('nat_pw', 'بالاو', 100, true),
  ('nat_pa', 'بنما', 100, true),
  ('nat_pg', 'بابوا غينيا الجديدة', 100, true),
  ('nat_py', 'باراغواي', 100, true),
  ('nat_pe', 'بيرو', 100, true),
  ('nat_ph', 'الفلبين', 100, true),
  ('nat_pl', 'بولندا', 100, true),
  ('nat_pt', 'البرتغال', 100, true),
  ('nat_ro', 'رومانيا', 100, true),
  ('nat_ru', 'روسيا', 100, true),
  ('nat_rw', 'رواندا', 100, true),
  ('nat_kn', 'سانت كيتس ونيفيس', 100, true),
  ('nat_lc', 'سانت لوسيا', 100, true),
  ('nat_vc', 'سانت فنسنت والغرينادين', 100, true),
  ('nat_ws', 'ساموا', 100, true),
  ('nat_sm', 'سان مارينو', 100, true),
  ('nat_st', 'ساو تومي وبرينسيبي', 100, true),
  ('nat_sn', 'السنغال', 100, true),
  ('nat_rs', 'صربيا', 100, true),
  ('nat_sc', 'سيشل', 100, true),
  ('nat_sl', 'سيراليون', 100, true),
  ('nat_sg', 'سنغافورة', 100, true),
  ('nat_sk', 'سلوفاكيا', 100, true),
  ('nat_si', 'سلوفينيا', 100, true),
  ('nat_sb', 'جزر سليمان', 100, true),
  ('nat_za', 'جنوب أفريقيا', 100, true),
  ('nat_ss', 'جنوب السودان', 100, true),
  ('nat_es', 'إسبانيا', 100, true),
  ('nat_lk', 'سريلانكا', 100, true),
  ('nat_sr', 'سورينام', 100, true),
  ('nat_se', 'السويد', 100, true),
  ('nat_ch', 'سويسرا', 100, true),
  ('nat_tj', 'طاجيكستان', 100, true),
  ('nat_tz', 'تنزانيا', 100, true),
  ('nat_th', 'تايلاند', 100, true),
  ('nat_tl', 'تيمور الشرقية', 100, true),
  ('nat_tg', 'توغو', 100, true),
  ('nat_to', 'تونغا', 100, true),
  ('nat_tt', 'ترينيداد وتوباغو', 100, true),
  ('nat_tr', 'تركيا', 100, true),
  ('nat_tm', 'تركمانستان', 100, true),
  ('nat_tv', 'توفالو', 100, true),
  ('nat_ug', 'أوغندا', 100, true),
  ('nat_ua', 'أوكرانيا', 100, true),
  ('nat_gb', 'المملكة المتحدة', 100, true),
  ('nat_us', 'الولايات المتحدة', 100, true),
  ('nat_uy', 'أوروغواي', 100, true),
  ('nat_uz', 'أوزبكستان', 100, true),
  ('nat_vu', 'فانواتو', 100, true),
  ('nat_va', 'الفاتيكان', 100, true),
  ('nat_ve', 'فنزويلا', 100, true),
  ('nat_vn', 'فيتنام', 100, true),
  ('nat_zm', 'زامبيا', 100, true),
  ('nat_zw', 'زيمبابوي', 100, true)
ON CONFLICT ("nameAr") DO NOTHING;
